export type Game = {
  _id: number;
  game: string;
  minPlayers: number;
  maxPlayers: number;
  type: number;
  minTime: number;
  maxTime: number;
  imgMain: string;
  imgs: string;
  desc: string;
  goodFor: string;
  subdesc: string;
  minAge: number;
  difficulty: number;
  site: string;
  scoreHands: number;
  score: number;
  designer: string;
  artist: string;
  editor: string;
  yearRelease: string;
  linkDownload: string;
  categoriaAluguel: number;
};
